name: image_downloader  

channels:
  - conda-forge

dependencies:
  - python
  - numpy
  - rasterio
  - geopandas
  - requests
  - shapely
  - earthaccess
  - gdal
  - libgdal-hdf4  # Added HDF4 driver for GDAL
  - pip
  - pip:
    - earthdata
